@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface Model <<Interface>>
Class Model
Class ModelManager
Class UserPrefs
Interface ReadOnlyUserPrefs<<Interface>>

Package PatientRecords {
Class PatientRecords
}

Package RoomList {
Class RoomList
}
}


Class HiddenOutside #FFFFFF
HiddenOutside ..> Model


ModelManager .up.|> Model
ModelManager o-left-> "1" UserPrefs
ModelManager o--> "1" PatientRecords
ModelManager o--> "1" RoomList
UserPrefs .up.|> ReadOnlyUserPrefs

@enduml
